import { format } from "date-fns";
import { Download, FileSpreadsheet, RefreshCw, AlertTriangle, Inbox } from "lucide-react";
import { cn } from "@/lib/utils";
import { TableSkeleton } from "@/components/TableSkeleton";
import { useDeliveryHistory } from "../hooks/useDeliveryHistory";
import { downloadBlob } from "@/lib/downloadBlob";
import { getErrorMessage } from "@/lib/errorParser";

export function FileHistoryTable() {
  const { data, isLoading, isError, error, isFetching } = useDeliveryHistory();

  if (isLoading) return <TableSkeleton rows={5} cols={5} />;

  if (isError) {
    const { title, description } = getErrorMessage(error);
    return (
      <div className="flex flex-col items-center gap-3 py-16 text-center">
        <AlertTriangle className="h-8 w-8 text-red-400" />
        <div>
          <p className="text-sm font-medium text-slate-800">{title}</p>
          <p className="text-xs text-slate-500">{description}</p>
        </div>
      </div>
    );
  }

  const items = data ?? [];

  return (
    <div className={cn("relative transition-opacity", isFetching && "opacity-70")}>
      {isFetching && (
        <div className="absolute right-0 top-0 flex items-center gap-1.5 text-xs text-slate-400">
          <RefreshCw className="h-3 w-3 animate-spin" />
          Refreshing…
        </div>
      )}

      {items.length === 0 ? (
        <EmptyHistory />
      ) : (
        <div className="overflow-x-auto rounded-2xl border border-slate-200">
          <table className="min-w-full divide-y divide-slate-100 text-sm">
            <thead className="bg-slate-50">
              <tr>
                {["File", "Records", "Generated", "Generated By", ""].map((h) => (
                  <th
                    key={h}
                    className="px-5 py-3.5 text-left text-xs font-semibold uppercase tracking-wider text-slate-500"
                  >
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 bg-white">
              {items.map((file) => (
                <tr key={file.id} className="group transition-colors hover:bg-slate-50">
                  {/* Filename */}
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-3">
                      <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-emerald-50">
                        <FileSpreadsheet className="h-4 w-4 text-emerald-600" />
                      </div>
                      <div className="min-w-0">
                        <p className="truncate font-medium text-slate-800">
                          {file.filename}
                        </p>
                        <p className="text-xs text-slate-400">Batch report</p>
                      </div>
                    </div>
                  </td>

                  {/* Record count */}
                  <td className="whitespace-nowrap px-5 py-4">
                    <span className="rounded-full bg-blue-50 px-2.5 py-0.5 text-xs font-semibold text-blue-700">
                      {file.record_count.toLocaleString()}
                    </span>
                  </td>

                  {/* Generated at */}
                  <td className="whitespace-nowrap px-5 py-4 text-xs">
                    <p className="text-slate-700">
                      {format(new Date(file.generated_at), "MMM d, yyyy")}
                    </p>
                    <p className="text-slate-400">
                      {format(new Date(file.generated_at), "h:mm a")}
                    </p>
                  </td>

                  {/* Generated by */}
                  <td className="whitespace-nowrap px-5 py-4 text-xs text-slate-500">
                    {file.generated_by ?? (
                      <span className="text-slate-300">—</span>
                    )}
                  </td>

                  {/* Download */}
                  <td className="whitespace-nowrap px-5 py-4">
                    {file.file_url ? (
                      <DownloadButton url={file.file_url} filename={file.filename} />
                    ) : (
                      <span className="text-xs text-slate-300">Unavailable</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}

// ── Download button ──────────────────────────────────────────────────────────

function DownloadButton({ url, filename }: { url: string; filename: string }) {
  async function handleClick() {
    const res = await fetch(url);
    const blob = await res.blob();
    downloadBlob(blob, filename);
  }

  return (
    <button
      onClick={() => void handleClick()}
      className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-600 transition-colors hover:border-blue-300 hover:bg-blue-50 hover:text-blue-700"
    >
      <Download className="h-3.5 w-3.5" />
      Download
    </button>
  );
}

// ── Empty state ──────────────────────────────────────────────────────────────

function EmptyHistory() {
  return (
    <div className="flex flex-col items-center gap-3 rounded-2xl border border-dashed border-slate-200 py-16">
      <div className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100">
        <Inbox className="h-6 w-6 text-slate-400" />
      </div>
      <div className="text-center">
        <p className="text-sm font-medium text-slate-700">No dispatches yet</p>
        <p className="text-xs text-slate-400">
          Dispatched reports will appear here once you send the first batch.
        </p>
      </div>
    </div>
  );
}
